function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Store Setup')
    .addItem('Validate Headers', 'validateHeaders')
    .addItem('Fix Headers', 'fixHeaders')
    .addSeparator()
    .addItem('Pull Products (Notion → Sheet)', 'pullNotionToSheet')
    .addItem('Push Products (Sheet → Notion)', 'pushSheetToNotion')
    .addItem('Two-way Sync (Push → Pull)', 'twoWaySync')
    .addSeparator()
    .addItem('Push Products (Batched)', 'pushProductsBatched')
    .addItem('Resume Batched Push', 'pushProductsBatchedResume')
    .addItem('Push Progress', 'pushProgressSummary')
    .addItem('Cancel Batched Push', 'cancelBatchedPush')
    .addSeparator()
    .addItem('Pull Manufacturers', 'pullManufacturers')
    .addItem('Push Manufacturers', 'pushManufacturers')
    .addSeparator()
    .addItem('Pull Devices', 'pullDevices')
    .addItem('Push Devices', 'pushDevices')
    .addSeparator()
    .addItem('Apply Edits (from Edits tab)', 'applyEditsFromEditsTab')
    .addItem('Insert TEST row', 'insertTestRow')
    .addToUi();
}